local-development:
  VITE_ENV: 'local-development'
  VITE_API_BASE_URL:
  VITE_STORAGE_URL:
  VITE_SITE_URL:

development:
  VITE_ENV: 'development'
  VITE_API_BASE_URL:
  VITE_STORAGE_URL:
  VITE_SITE_URL:
