local-development:
  VITE_ENV: 'local-development'
  VITE_API_BASE_URL: 'http://localhost:8080'
  VITE_CLOUDINARY_CLOUD_NAME: 'dji7b01wu'
  VITE_CLOUDINARY_UPLOAD_PRESET: 'shopO_dough'
  VITE_STORAGE_URL:
  VITE_SITE_URL:

development:
  VITE_ENV: 'development'
  VITE_API_BASE_URL:
  VITE_CLOUDINARY_CLOUD_NAME: 'dji7b01wu'
  VITE_CLOUDINARY_UPLOAD_PRESET: 'shopO_dough'
  VITE_STORAGE_URL:
  VITE_SITE_URL:
