#!/usr/bin/env sh

# Source Husky script
. "$(dirname -- "$0")/_/husky.sh" || exit 1

# Change to project root directory and run commitlint
cd "$(dirname -- "$0")/.." || exit 1
npx --no -- commitlint --edit "${1}" || exit 1
